[models]
  [models.llm]
    [models.llm."chatglm-6b"]
    type = "huggingface"
    path = "THUDM/chatglm-6b"
    [models.llm."chatglm-6b-int8"]
    type = "huggingface"
    path = "THUDM/chatglm-6b-int8"
    [models.llm."chatglm-6b-int4"]
    type = "huggingface"
    path = "THUDM/chatglm-6b-int4"

  [models.embeddings]
    [models.embeddings."text2vec-large-chinese"]
    type = "huggingface"
    path = "GanymedeNil/text2vec-large-chinese"

[auth]
tokens = ["token1"]

[tunnel]
  [tunnel.ngrok]
  token = ""
  region = "jp"
  # Binding custom subdomains is a feature for paid accounts.
  subdomain = ""
  [tunnel.cloudflare]
  # first need init cloudflare tunnel, see README.md
  cloudflared_path = "/usr/local/bin/cloudflared"
  # tunnel name, see README.md
  name = "chatglm-openai-api"
